# Data to monitor

COINMARKETCAP = {
    "WATCH": [
        "LTC",
        "BCH",
        "XMR",
        "NEBL",
        "OCN",
        "BLZ",
        "ETC"
        "BNB",
        "BTC",
        "LINK",
        "DRGN",
        "ENJ",
        "EOS",
        "ETH",
        "GAS",
        "ICX",
        "JNT",
        "NANO",
        "NEO",
        "ODN",
        "OMG",
        "POLY",
        "REQ",
        "AGI",
        "VEN",
        "WTC",
        "ZIL",
        "ZCL",
        "XRP"
    ],
    "CORR": [
        "BTC",
        "BCH",
        "ETH",
        "ETC",
        "XRP",
        "LTC",
        "ADA",
        "XLM",
        "EOS",
        "XMR",
        "NEO",
        "GAS",
        "OMG",
        "NANO",
        "ICX",
        "ZCL",
        "DRGN",
        "AST",
        "ODN"
    ],
    "PORTFOLIO": {
        "BNB": 11.17,
        "BTC": 6.90920,
        "LINK": 9500,
        "COV": 640.0,
        "DBC": 1250.57,
        "DRGN": 1319.65,
        "ENJ": 19948.00,
        "EOS": 247.29,
        "ETH": 7.08,
        "GAS": 0.8556,
        "ICX": 1260.03,
        "JNT": 749.25,
        "NANO": 3319.68,
        "NEO": 100.00,
        "ODN": 8637.0,
        "OMG": 77.2,
        "POLY": 3906.21,
        "REQ": 2529.44,
        "SAFEX": 17707.00,
        "AGI": 4735.75,
        "VEN": 481.00,
        "WTC": 100.00,
        "ZIL": 34721.56,
        "ZCL": 137
    }
}

BINANCE = {
    "CANDLES": [
        "BTCUSDT",
        "ETHUSDT",
        "BNBUSDT",
        "LTCUSDT",
        "BCCUSDT",
        "ETHBTC",
        "EOSBTC",
        "ICXBTC",
        "LINKBTC",
        "VENBTC",
        "XRPBTC",
        "NANOBTC",
        "NANOETH",
        "NEOBTC",
        "OMGBTC",
        "BLZBTC",
        "ETCBTC",
        "XMRBTC",
        "NEBLBTC",
        "WTCBTC",
        "NCASHBTC",
        "ZECBTC"
    ]
}
